### PR TITLE
Improved visual quality for scaled text and bugs

### PR DESCRIPTION
**Pull request by johnrobinsn**
See textscale.js example.
- Separated glyph texture caching from glyph metric caching.
- Glyph textures are no longer one for one with a glyph's pixelSize.  A given pixelSize glyph may use the texture from a larger pixelSize glyph.  This reduces overall memory and provides more pixel data for sampling.
- Glyph rendering is done using the exact metrics for the specific pixelSize as reported by free type.  The selected glyph texture (which may be for a larger pixelSize) is scaled (down) to fit inside the glyph bounding box for the specificed pixelSize.
- Glyph texture selection now takes into account the necessary LOD (Level of Detail) needed based on sx and sy scale factors.  Greatly improving visual quality when scaling text.

### CODE REVIEW

**Comment by johnrobinsn** [comment]
Connie can you review this and run through all of the text measurement regression tests and merge it if all things look good.

**Comment by conniefry** [comment]
Functionally, the tests look good so far; but, I'm seeing a significant degradation in performance in some tests.

**Comment by johnrobinsn** [comment]
Which tests are you seeing a performance hit?

**Comment by johnrobinsn** [comment]
Fixed a bug where glyph cache wasn't being populated.

**Pull request merged**
